version: '3.8'

services:
  apple-music-mcp:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: apple-music-mcp
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-3600}:${SERVER_PORT:-3600}"
    env_file:
      - ../.env
    volumes:
      - ./keys:/keys:ro
    networks:
      - mcp_network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:$${SERVER_PORT:-3600}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mcp_network:
    driver: bridge